dataset_path: "/home/mukhtar/Downloads/CLabNormHist_iteration_202/dataset_colorLabNormalHist.yml"
classifier_path: "/home/mukhtar/Downloads/CLabNormHist_iteration_202/gmm_archive_colorLabNormalHist"
classifier_modality: "colorLabNormalHist"
classifier_sample_size: 30
modality: "colorLabNormalHist"
sample_size: 30
number_of_iteration: 100
sv:
  use_transform: false
  voxel_resolution: 0.008
  color_importance: 0.2
  spatial_importance: 0.4
  normal_importance: 0.4
  seed_resolution: 0.05
workspace:
  sphere:
    x: 0.065
    y: -0.05
    z: 1.1
    radius: 0.6
    threshold: 0.0
  csg_intersect_cuboid:
    x_min: -0.40
    x_max: 0.20
    y_min: -0.30
    y_max: 0.00
    z_min: -0.2
    z_max: 1.5
