classifier_path: "/home/jonathan/Documents/STA3/crusty_babbling/iteration_72/dataset_normal.yml"
number_of_iteration: 100
sv:
  use_transform: false
  voxel_resolution: 0.008
  color_importance: 0.2
  spatial_importance: 0.4
  normal_importance: 0.4
  seed_resolution: 0.05
workspace:
  sphere:
    x: 0.065
    y: -0.05
    z: 1.1
    radius: 0.6
    threshold: 0.0
  csg_intersect_cuboid:
    x_min: -0.34
    x_max: 0.36
    y_min: 0.11
    y_max: 0.35
    z_min: -0.2
    z_max: 1.5
